language: python
python:
  - "2.7"

services:
  - mysql

before_install:
  - mysql -u root -e "CREATE DATABASE IF NOT EXISTS pruebaheadless;"
  - mysql -u root -e "CREATE USER 'usuario'@'localhost' IDENTIFIED BY 'usuario';"
  - mysql -u root -e "grant all privileges on pruebaheadless.* to 'usuario'@'localhost'";
  - mysql -u root -e "grant all privileges on test_pruebaheadless.* to 'usuario'@'localhost'";
  - mysql -u root -e "FLUSH PRIVILEGES;"
install: 
  - sudo apt-get install xvfb
  - sudo dpkg -i lib/lib/google-chrome-stable_current_amd64.deb
  - sudo apt-get install -f

before_script: 
  

script: 
  - # chmod +x lib/lib/*
  - # ls -la lib/lib/*
  - # export PATH=$PATH:$(pwd)/lib/lib
  - # echo $PATH
  - virtualenv entornito
  - . entornito/bin/activate
  - pip install -r requirements.txt
  - Xvfb :0 >& /dev/null &
  - export DISPLAY=:0
  - export MI_PUERTO=8000
  - python manage.py migrate
  - echo "from django.contrib.auth.models import User; User.objects.create_superuser('alex', 'alex@example.com', 'alexcontra')" | python manage.py shell
  - python manage.py runserver 127.0.0.1:$MI_PUERTO &
  - lettuce ft/tests

notifications:
email: false

