# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosLaborales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=100, verbose_name='Puesto')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Salario')),
            ],
        ),
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=13, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('colonia', models.CharField(max_length=50, verbose_name='Colonia')),
            ],
        ),
    ]
