# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosOtros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otro', models.CharField(max_length=100, verbose_name='Otro')),
            ],
        ),
    ]
